#!/usr/bin/env bash
# Script: Display /etc/passwd

while IFS=':' read -r username password userid groupid userinfo homedirectory usershell; do
    echo "The user $username is part of the $groupid gang, lives in $homedirectory and rides $usershell. User ID's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd

