#!/usr/bin/env bash
# Display the content of the file /etc/passwd using the while loop + IFS

IFS=':'
while IFS=':' read -r username password _ groupid userinfo homedirectory usershell
do
  echo "The user $username is part of the $groupid gang, lives in $homedirectory and rides $usershell. User ID's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
