#!/usr/bin/env bash
# Script: Group visitors by IP and HTTP status code

if [ -s access.log ]; then
  awk '{ count[$1 " " $9]++ } END { for (key in count) print count[key], key }' access.log | sort -nr
else
  if [ -f access.log ]; then
    echo "0 chars for $(basename access.log)"
  else
    echo "wrong format log file"
  fi
fi
