#!/usr/bin/env bash
# Script: Group visitors by IP and HTTP status code

LOG_FILE="access.log"

if [[ ! -f "$LOG_FILE" ]]; then
  echo "wrong format log file"
else
  if [[ ! -s "$LOG_FILE" ]]; then
    echo "0 chars for small log file"
  else
    awk '{ count[$1 " " $9]++ } END { for (key in count) print count[key], key }' "$LOG_FILE" | sort -nr
  fi
fi
