#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0
minute=0

while [ $hour -le 12 ]; do
  printf "Hour: %d\n" $hour

  if [ $hour -eq 0 ]; then
    minute=1
  else
    minute=0
  fi

  while [ $minute -le 59 ]; do
    printf "%d\n" $minute
    minute=$((minute + 1))

    # Display only the first 70 lines
    if [ $hour -eq 5 ] && [ $minute -eq 59 ]; then
      exit
    fi
  done
