#!/usr/bin/env bash
# Script: Display Time

hours=0

while [ $hours -le 12 ]; do
    minutes=1
    while [ $minutes -le 59 ]; do
        printf "Hour: %02d\n" $hours
        printf "%02d\n" $minutes
        ((minutes++))
    done
    ((hours++))
done | head -n 70

