#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hours=0
minutes=1

while [ $hours -le 12 ]
do
    while [ $minutes -le 59 ]
    do
        printf "%02d:%02d\n" $hours $minutes
        minutes=$((minutes+1))

        # Display only the first 70 lines
        if [ $((hours * 60 + minutes)) -eq 70 ]; then
            exit
        fi
    done

    minutes=0
    hours=$((hours+1))
done

