#!/usr/bin/env bash
# Bash script manages manage_my_process
start
        # Start manage_my_process
        ./manage_my_process &
        # Save the PID to a file
        echo $! > /var/run/my_process.pid
        # Display message
        echo "manage_my_process started"
        
    stop
        # Stop manage_my_process
        kill $(cat /var/run/my_process.pid)
        # Delete the PID file
        rm /var/run/my_process.pid
        # Display message
        echo "manage_my_process stopped"
        
    restart
        # Stop manage_my_process
        kill $(cat /var/run/my_process.pid)
        # Delete the PID file
        rm /var/run/my_process.pid
        # Start manage_my_process
        ./manage_my_process &
        # Save the PID to a file
        echo $! > /var/run/my_process.pid
        # Display message
        echo "manage_my_process restarted"
        
    *
        # Display usage message
        echo "Usage: $0 {start|stop|restart}"
        
